set(SL_TARGET_ID x86_64-linux-gnu CACHE STRING "" FORCE)
include("${CMAKE_CURRENT_LIST_DIR}/bootlin-linux.cmake")
execute_process(COMMAND "${CMAKE_CURRENT_LIST_DIR}/../../scripts/cpkt-aflpp.sh" discover
  RESULT_VARIABLE _softline_afl_result OUTPUT_VARIABLE _softline_afl ERROR_VARIABLE _softline_afl_error)
if(NOT _softline_afl_result EQUAL 0)
  message(FATAL_ERROR "Unable to provision pinned AFL++: ${_softline_afl_error}")
endif()
function(_softline_afl_value key output)
  string(REPLACE "\n" ";" _softline_afl_lines "${_softline_afl}")
  set(_softline_afl_value "")
  foreach(_softline_afl_line IN LISTS _softline_afl_lines)
    if(_softline_afl_line MATCHES "^${key}=(.*)$")
      set(_softline_afl_value "${CMAKE_MATCH_1}")
      break()
    endif()
  endforeach()
  if(_softline_afl_value STREQUAL "")
    message(FATAL_ERROR "AFL++ resolver did not report ${key}")
  endif()
  set(${output} "${_softline_afl_value}" PARENT_SCOPE)
endfunction()

foreach(_softline_key cc cxx helper)
  _softline_afl_value("${_softline_key}" "_softline_afl_${_softline_key}")
endforeach()
set(ENV{AFL_PATH} "${_softline_afl_helper}")
set(CMAKE_C_COMPILER "${_softline_afl_cc}" CACHE FILEPATH "Pinned AFL++ C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${_softline_afl_cxx}" CACHE FILEPATH "Pinned AFL++ C++ compiler" FORCE)
