include_guard(GLOBAL)

# External verification dependencies share the lifecycle archive cache.  The
# cache contains only checksum-verified immutable archives; extraction remains
# under an individual build tree.
if(NOT DEFINED CPKT_DEPENDENCY_CACHE)
  if(DEFINED ENV{CPKT_DEPENDENCY_CACHE})
    set(CPKT_DEPENDENCY_CACHE "$ENV{CPKT_DEPENDENCY_CACHE}")
  elseif(DEFINED ENV{XDG_CACHE_HOME})
    set(CPKT_DEPENDENCY_CACHE "$ENV{XDG_CACHE_HOME}/c.pkt.systems/deps")
  else()
    set(CPKT_DEPENDENCY_CACHE "$ENV{HOME}/.cache/c.pkt.systems/deps")
  endif()
endif()
set(CPKT_DEPENDENCY_CACHE "${CPKT_DEPENDENCY_CACHE}" CACHE PATH
  "Verified dependency archives")

function(softline_verified_archive url digest name output)
  set(directory "${CPKT_DEPENDENCY_CACHE}/archives/sha256/${digest}")
  set(archive "${directory}/${name}")
  if(EXISTS "${archive}")
    file(SHA256 "${archive}" actual)
    if(actual STREQUAL digest)
      set(${output} "${archive}" PARENT_SCOPE)
      return()
    endif()
    message(FATAL_ERROR "Corrupt cached archive: ${archive}; expected ${digest}")
  endif()
  file(MAKE_DIRECTORY "${CPKT_DEPENDENCY_CACHE}/locks" "${directory}")
  file(LOCK "${CPKT_DEPENDENCY_CACHE}/locks/${digest}.lock" GUARD FUNCTION TIMEOUT 600)
  if(EXISTS "${archive}")
    file(SHA256 "${archive}" actual)
    if(actual STREQUAL digest)
      set(${output} "${archive}" PARENT_SCOPE)
      return()
    endif()
    message(FATAL_ERROR "Corrupt cached archive: ${archive}")
  endif()
  string(RANDOM LENGTH 12 nonce)
  set(temporary "${directory}/download-${nonce}")
  file(DOWNLOAD "${url}" "${temporary}" TLS_VERIFY ON STATUS status TIMEOUT 120)
  list(GET status 0 code)
  if(code EQUAL 0)
    file(SHA256 "${temporary}" actual)
  endif()
  if(NOT code EQUAL 0 OR NOT actual STREQUAL digest)
    file(REMOVE "${temporary}")
    message(FATAL_ERROR "Cannot acquire ${url}: ${status}; expected ${digest}")
  endif()
  file(RENAME "${temporary}" "${archive}")
  set(${output} "${archive}" PARENT_SCOPE)
endfunction()
