include_guard(GLOBAL)

# External dependencies share one verified-archive cache.  Each CMake root
# resolves it exactly once; this helper only consumes that resolved contract.
function(softline_configure_dependency_cache)
  if(DEFINED CPKT_DEPENDENCY_CACHE)
    set(_softline_dependency_cache "${CPKT_DEPENDENCY_CACHE}")
  elseif(DEFINED ENV{CPKT_DEPENDENCY_CACHE} AND
         NOT "$ENV{CPKT_DEPENDENCY_CACHE}" STREQUAL "")
    set(_softline_dependency_cache "$ENV{CPKT_DEPENDENCY_CACHE}")
  elseif(DEFINED ENV{XDG_CACHE_HOME} AND NOT "$ENV{XDG_CACHE_HOME}" STREQUAL "")
    set(_softline_dependency_cache "$ENV{XDG_CACHE_HOME}/c.pkt.systems/deps")
  elseif(DEFINED ENV{HOME} AND NOT "$ENV{HOME}" STREQUAL "")
    set(_softline_dependency_cache "$ENV{HOME}/.cache/c.pkt.systems/deps")
  else()
    message(FATAL_ERROR
      "CPKT_DEPENDENCY_CACHE is unset and neither XDG_CACHE_HOME nor HOME is available")
  endif()
  set(CPKT_DEPENDENCY_CACHE "${_softline_dependency_cache}" CACHE PATH
    "Verified dependency archives")
endfunction()

function(softline_verified_archive component url digest name output)
  if(NOT DEFINED CPKT_DEPENDENCY_CACHE OR CPKT_DEPENDENCY_CACHE STREQUAL "")
    message(FATAL_ERROR
      "${component}: CPKT_DEPENDENCY_CACHE must be configured by the CMake root")
  endif()
  set(directory "${CPKT_DEPENDENCY_CACHE}/archives/sha256/${digest}")
  set(archive "${directory}/${name}")
  if(EXISTS "${archive}")
    file(SHA256 "${archive}" actual)
    if(actual STREQUAL digest)
      set(${output} "${archive}" PARENT_SCOPE)
      return()
    endif()
  endif()
  file(MAKE_DIRECTORY "${CPKT_DEPENDENCY_CACHE}/locks" "${directory}")
  file(LOCK "${CPKT_DEPENDENCY_CACHE}/locks/${digest}.lock" GUARD FUNCTION TIMEOUT 600)
  if(EXISTS "${archive}")
    file(SHA256 "${archive}" actual)
    if(actual STREQUAL digest)
      set(${output} "${archive}" PARENT_SCOPE)
      return()
    endif()
    file(REMOVE "${archive}")
  endif()
  string(RANDOM LENGTH 12 nonce)
  set(temporary "${directory}/download-${nonce}")
  set(transient_codes 5 6 7 18 28 35 52 55 56 92)
  foreach(attempt RANGE 1 3)
    file(REMOVE "${temporary}")
    file(DOWNLOAD "${url}" "${temporary}" TLS_VERIFY ON STATUS status TIMEOUT 120)
    list(GET status 0 code)
    list(FIND transient_codes "${code}" transient)
    if(code EQUAL 0 OR transient EQUAL -1)
      break()
    endif()
  endforeach()
  if(code EQUAL 0)
    file(SHA256 "${temporary}" actual)
  endif()
  if(NOT code EQUAL 0 OR NOT actual STREQUAL digest)
    file(REMOVE "${temporary}")
    message(FATAL_ERROR
      "${component}: cannot acquire ${url}; expected ${digest}; cache ${archive}; ${status}")
  endif()
  file(RENAME "${temporary}" "${archive}")
  set(${output} "${archive}" PARENT_SCOPE)
endfunction()
